#!/usr/bin/env python3
"""
conformance_cli.py - check a built dhow against proto/.

Usage:
    scripts/conformance_cli.py [path to dhow]

Builds one if no path is given.

# Why this exists

`check_spec.py` checks that the specification documents agree with themselves.
`conformance_test.py` checks that the golden vectors agree with the documents.
Both are worth having and **neither would notice if the implementation had
drifted from both**: the vectors are generated by a script that encodes the same
assumptions the documents do, so the two can be consistently wrong together.

This runs a real transfer with a real binary and reads the bytes it produced at
the offsets `proto/` declares. If the manifest's version byte is not at offset 4,
or its CRC does not cover exactly bytes 0..160, or a frame's payload length is
not at offset 40, it fails - against the binary, not against a description of it.

It is also the suite a third party runs against *their* implementation. Point it
at another binary and it checks that one instead.
"""

import os
import struct
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# --- What proto/ declares. Restated here on purpose. ---
#
# These constants are transcribed from the documents rather than imported from
# the code. Importing them would make this suite agree with the implementation
# by construction, which is exactly the failure it exists to catch.

FRAME_MAGIC = b"DHOW"
FRAME_VERSION = 1
FRAME_HEADER_SIZE = 46
FRAME_OFF_MAGIC = 0
FRAME_OFF_VERSION = 4
FRAME_OFF_TYPE = 5
FRAME_OFF_RESERVED = 6
FRAME_OFF_SESSION = 8
FRAME_OFF_MAC = 24
FRAME_OFF_BLOCK = 32
FRAME_OFF_SYMBOL = 36
FRAME_OFF_PAYLOAD_LEN = 40
FRAME_OFF_CRC = 42

MANIFEST_MAGIC = b"DHMF"
MANIFEST_VERSION = 2
MANIFEST_HEADER_SIZE = 228
MANIFEST_OFF_VERSION = 4
MANIFEST_OFF_RESERVED1 = 5
MANIFEST_OFF_SESSION = 8
MANIFEST_OFF_FILE_COUNT = 24
MANIFEST_OFF_TOTAL_SIZE = 28
MANIFEST_OFF_PAYLOAD_DIGEST = 36
MANIFEST_OFF_SALT = 68
MANIFEST_OFF_NONCE = 100
MANIFEST_OFF_PAYLOAD_SIZE = 124
MANIFEST_OFF_BLOCK_COUNT = 132
MANIFEST_OFF_SYMBOL_SIZE = 136
MANIFEST_OFF_RESERVED2 = 158
MANIFEST_OFF_CRC = 160
MANIFEST_OFF_SIGNATURE = 164
MANIFEST_ENTRY_FIXED = 43  # 2 + 8 + 32 + 1, beyond the name

CRC32C_POLY = 0x82F63B78

FAILURES = []


def fail(message: str) -> None:
    FAILURES.append(message)
    print(f"  FAIL  {message}")


def ok(message: str) -> None:
    print(f"  ok    {message}")


def crc32c(data: bytes) -> int:
    """CRC32C, written out rather than imported, for the same reason as above."""
    crc = 0xFFFFFFFF
    for byte in data:
        crc ^= byte
        for _ in range(8):
            crc = (crc >> 1) ^ (CRC32C_POLY if crc & 1 else 0)
    return crc ^ 0xFFFFFFFF


def run(binary: str, *args: str, expect: int = 0) -> subprocess.CompletedProcess:
    result = subprocess.run(
        [binary, *args], capture_output=True, text=True, check=False
    )
    if result.returncode != expect:
        fail(
            f"`dhow {' '.join(args[:2])}` exited {result.returncode}, "
            f"expected {expect}: {result.stderr.strip()[:200]}"
        )
    return result


def build_binary() -> str:
    """Builds dhow into a temporary path and returns it."""
    out = os.path.join(tempfile.mkdtemp(prefix="dhow-conf-"), "dhow")
    subprocess.run(
        ["cargo", "build", "--release", "--quiet",
         "--manifest-path", os.path.join(ROOT, "core", "Cargo.toml"), "-p", "dhow-ffi"],
        check=True,
    )
    subprocess.run(
        ["go", "build", "-o", out, "./cli/cmd/dhow"], cwd=ROOT, check=True
    )
    return out


def check_frame(frame: bytes, name: str, session_id: bytes) -> None:
    """Checks one frame against proto/frame.md."""
    if len(frame) < FRAME_HEADER_SIZE:
        fail(f"{name} is {len(frame)} bytes, below the {FRAME_HEADER_SIZE}-byte header")
        return

    if frame[FRAME_OFF_MAGIC:FRAME_OFF_MAGIC + 4] != FRAME_MAGIC:
        fail(f"{name} magic is {frame[0:4]!r}, expected {FRAME_MAGIC!r}")
    if frame[FRAME_OFF_VERSION] != FRAME_VERSION:
        fail(f"{name} version is {frame[FRAME_OFF_VERSION]}, expected {FRAME_VERSION}")
    if frame[FRAME_OFF_RESERVED:FRAME_OFF_RESERVED + 2] != b"\x00\x00":
        fail(f"{name} reserved bytes at offset 6 are not zero")

    got_session = frame[FRAME_OFF_SESSION:FRAME_OFF_SESSION + 16]
    if got_session != session_id:
        fail(f"{name} session id is {got_session.hex()}, expected {session_id.hex()}")

    declared = struct.unpack_from("<H", frame, FRAME_OFF_PAYLOAD_LEN)[0]
    carried = len(frame) - FRAME_HEADER_SIZE
    if declared != carried:
        fail(f"{name} declares {declared} payload bytes and carries {carried}")

    # The CRC covers the payload, per frame.md. Recomputing it here is what
    # catches an implementation that covers the header as well, or nothing.
    declared_crc = struct.unpack_from("<I", frame, FRAME_OFF_CRC)[0]
    actual = crc32c(frame[FRAME_HEADER_SIZE:])
    if declared_crc != actual:
        fail(
            f"{name} CRC is {declared_crc:#010x}; CRC32C over its payload is "
            f"{actual:#010x}. The CRC covers the payload only."
        )


def check_manifest(data: bytes, session_id: bytes, files: int) -> None:
    """Checks a manifest against proto/manifest.md."""
    if len(data) < MANIFEST_HEADER_SIZE:
        fail(f"manifest is {len(data)} bytes, below the {MANIFEST_HEADER_SIZE}-byte header")
        return

    if data[0:4] != MANIFEST_MAGIC:
        fail(f"manifest magic is {data[0:4]!r}, expected {MANIFEST_MAGIC!r}")
    else:
        ok("manifest magic at offset 0")

    if data[MANIFEST_OFF_VERSION] != MANIFEST_VERSION:
        fail(
            f"manifest version is {data[MANIFEST_OFF_VERSION]}, expected "
            f"{MANIFEST_VERSION}. The suite is frozen at 2.0."
        )
    else:
        ok(f"manifest version {MANIFEST_VERSION} at offset {MANIFEST_OFF_VERSION}")

    if data[MANIFEST_OFF_RESERVED1:MANIFEST_OFF_RESERVED1 + 3] != b"\x00\x00\x00":
        fail("manifest reserved bytes at offset 5 are not zero")
    if data[MANIFEST_OFF_RESERVED2:MANIFEST_OFF_RESERVED2 + 2] != b"\x00\x00":
        fail("manifest reserved bytes at offset 158 are not zero")
    else:
        ok("manifest reserved fields are zero")

    got_session = data[MANIFEST_OFF_SESSION:MANIFEST_OFF_SESSION + 16]
    if got_session != session_id:
        fail(f"manifest session id is {got_session.hex()}, expected {session_id.hex()}")
    else:
        ok("manifest session id matches the one send reported")

    count = struct.unpack_from("<I", data, MANIFEST_OFF_FILE_COUNT)[0]
    if count != files:
        fail(f"manifest declares {count} files, {files} were sent")
    else:
        ok(f"manifest file count is {count}")

    # The CRC covers bytes 0..160 exactly. An implementation that covered the
    # signature too, or stopped at 100 as v1 did, fails here.
    declared_crc = struct.unpack_from("<I", data, MANIFEST_OFF_CRC)[0]
    actual = crc32c(data[:MANIFEST_OFF_CRC])
    if declared_crc != actual:
        fail(
            f"manifest CRC is {declared_crc:#010x}; CRC32C over bytes 0..{MANIFEST_OFF_CRC} "
            f"is {actual:#010x}"
        )
    else:
        ok(f"manifest CRC covers bytes 0..{MANIFEST_OFF_CRC}")

    signature = data[MANIFEST_OFF_SIGNATURE:MANIFEST_OFF_SIGNATURE + 64]
    if signature == bytes(64):
        fail("manifest signature is all zeros; it was not signed")
    else:
        ok("manifest carries a signature at offset 164")

    # Walk the entries and confirm the manifest ends exactly at the last one.
    offset = MANIFEST_HEADER_SIZE
    total = 0
    for i in range(count):
        if offset + 2 > len(data):
            fail(f"manifest entry {i} starts past the end of the buffer")
            return
        name_len = struct.unpack_from("<H", data, offset)[0]
        entry_len = MANIFEST_ENTRY_FIXED + name_len
        if offset + entry_len > len(data):
            fail(f"manifest entry {i} declares {name_len} name bytes and runs past the end")
            return
        total += struct.unpack_from("<Q", data, offset + 2 + name_len)[0]
        flags = data[offset + 42 + name_len]
        if flags & ~1:
            fail(f"manifest entry {i} sets undefined flag bits {flags:#04x}")
        offset += entry_len

    if offset != len(data):
        fail(f"manifest has {len(data) - offset} trailing bytes after its last entry")
    else:
        ok(f"manifest ends exactly at entry {count - 1}")

    declared_total = struct.unpack_from("<Q", data, MANIFEST_OFF_TOTAL_SIZE)[0]
    if declared_total != total:
        fail(f"manifest declares {declared_total} total bytes; entries sum to {total}")
    else:
        ok("manifest total size matches the sum of its entries")


def main() -> int:
    binary = sys.argv[1] if len(sys.argv) > 1 else None

    print("=== dhow CLI conformance ===")
    print("checking a built binary against proto/, not against the vectors")
    print()

    if binary is None:
        print("building dhow...")
        binary = build_binary()
    print(f"binary: {binary}")
    print()

    work = tempfile.mkdtemp(prefix="dhow-conf-work-")
    data = os.path.join(work, "data")
    os.makedirs(os.path.join(data, "nested"))
    with open(os.path.join(data, "blob.bin"), "wb") as f:
        f.write(bytes((i * 7 + 3) % 251 for i in range(5000)))
    with open(os.path.join(data, "nested", "note.txt"), "w") as f:
        f.write("conformance\n")
    script = os.path.join(data, "run.sh")
    with open(script, "w") as f:
        f.write("#!/bin/sh\nexit 0\n")
    os.chmod(script, 0o755)
    file_count = 3

    operator = os.path.join(work, "operator.key")
    identity = os.path.join(work, "sender.key")
    public = os.path.join(work, "sender.pub")
    frames = os.path.join(work, "frames")

    run(binary, "keygen", "-out", operator, "-quiet")
    run(binary, "keygen", "-kind", "identity", "-out", identity, "-quiet")

    print("send:")
    result = run(
        binary, "send", "-key", operator, "-identity", identity,
        "-in", data, "-out", frames, "-symbol-size", "256", "-blocks", "2",
        "-overhead", "20", "-json",
    )
    import json

    sent = json.loads(result.stdout)
    session_id = bytes.fromhex(sent["session_id"])
    ok(f"send reported session {sent['session_id']}")

    with open(os.path.join(frames, "manifest.bin"), "rb") as f:
        manifest = f.read()
    check_manifest(manifest, session_id, file_count)

    print()
    print("frames:")
    names = sorted(n for n in os.listdir(frames) if n.startswith("frame-"))
    if not names:
        fail("send produced no frames")
    else:
        ok(f"send produced {len(names)} frames")
    # Every frame, not a sample: they are cheap to check and a format defect
    # that only affects the last block would survive a sample.
    for name in names:
        with open(os.path.join(frames, name), "rb") as f:
            check_frame(f.read(), name, session_id)
    if not FAILURES:
        ok(f"all {len(names)} frames match proto/frame.md")

    print()
    print("recv and verify:")
    received = os.path.join(work, "received")
    run(binary, "recv", "-key", operator, "-signer", public,
        "-in", frames, "-out", received, "-quiet")
    ok("recv completed")

    run(binary, "verify", "-in", frames, "-signer", public, "-dir", received, "-quiet")
    ok("verify accepted the received dataset")

    # The policy in proto/README.md says a receiver rejects a wrong version
    # byte. Checked against the binary rather than assumed from the code.
    print()
    print("policy:")
    bad = os.path.join(work, "bad-frames")
    subprocess.run(["cp", "-R", frames, bad], check=True)
    with open(os.path.join(bad, "manifest.bin"), "r+b") as f:
        f.seek(MANIFEST_OFF_VERSION)
        f.write(bytes([MANIFEST_VERSION + 1]))
    run(binary, "recv", "-key", operator, "-signer", public,
        "-in", bad, "-out", os.path.join(work, "nope"), expect=3)
    if os.path.exists(os.path.join(work, "nope")):
        fail("a rejected manifest still produced output")
    else:
        ok("a manifest with an unknown version is rejected, and writes nothing")

    print()
    if FAILURES:
        print(f"=== CLI CONFORMANCE FAILED: {len(FAILURES)} problem(s) ===")
        return 1
    print("=== CLI CONFORMANCE PASSED ===")
    return 0


if __name__ == "__main__":
    sys.exit(main())
